// <auto-generated />
namespace PFDC.LolaAppWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class calendar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(calendar));
        
        string IMigrationMetadata.Id
        {
            get { return "202109211432444_calendar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
