// <auto-generated />
namespace PFDC.LolaAppWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class actalizaciónuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(actalizaciónuser));
        
        string IMigrationMetadata.Id
        {
            get { return "202107252231535_actalización user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
